function [] = PrintAccuracy( split, accuracies, name )
%PRINTACCURACY

fprintf( '%11s: %s= %6.2f%%, %s= %6.2f%%, mean= %6.2f%%\n', ...
    name, ...
    split.names{1}, ...
    accuracies(1), ...
    split.names{2}, ...
    accuracies(2), ...
    accuracies(3) ...
    );

end

